### ISSUE TITLE
Release 0.2.0

### ISSUE THREAD

**Issue by mooyoul** [mooyoul/angulartics-facebook-pixel#6]
:)

**Comment by niemyjski** [comment]
I need this so I can track events

**Comment by niemyjski** [comment]
can you please push this out

**Comment by maelfrize** [comment]
:+1:

**Comment by mooyoul** [comment]
I'm going to release 0.2.0.

**To-do**
- [x] Update dependencies
- [x] Remove `version` property from bower.json 
- [x] Update documentation
- [x] Update example
- [x] Change version
- [x] Release/tag new version
- [x] Release new version to Bower/NPM

**Comment by mooyoul** [comment]
I've just landed v0.2.0 of angulartics-facebook-pixel!   🎉 
Now you can install `angulartics-facebook-pixel@0.2.0` from NPM or Bower.

Thanks for your patience! @niemyjski @maelfrize
